package yggdrasill: json5;

world json5 {
  import print: func(msg: string);

  export run: func();
}


interface ast {
  resource source-span {
    get: func() -> string;
  }
  resource cst-node {

  }
  record a-node {
    node: borrow<cst-node>
  }

}


// a = [a-z] . [z-z]