[package]
name = "rusty-nix"
version = "0.1.0"
edition = "2021"

[dependencies]
nyar-vm = { workspace = true }
nyar-types = { workspace = true }
oak-core = { workspace = true }
oak-nix = { workspace = true }
chomsky = { workspace = true }
chomsky-uir = { workspace = true }
serde = { workspace = true }
