[package]
name = "rusty-go"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nyar-vm = { workspace = true }
nyar-aot = { workspace = true }
nyar-types = { workspace = true }
oak-core = { workspace = true }
oak-vfs = { workspace = true }
oak-go = { workspace = true }
oak-repl = { workspace = true }
chomsky = { workspace = true }
chomsky-types = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-extract = { workspace = true }
chomsky-cost = { workspace = true }
serde = { workspace = true }

[lib]
path = "src/lib.rs"
