[workspace]
resolver = "2"
members = [
    "projects/*",
    "examples/rusty-csharp",
    "examples/rusty-go",
    "examples/rusty-rust",
    "examples/rusty-typescript",
]
default-members = [
    "projects/nyar-types",
    "projects/nyar-vm",
]
exclude = ["examples/valkyrie-bootstrap", "projects/nyar-tools"]

[profile.release]
lto = true
opt-level = "s"

[workspace.dependencies]
chomsky = { path = "../ProjectChomsky/packages/chomsky" }
chomsky-source = { path = "../ProjectChomsky/packages/chomsky-source" }
chomsky-uir = { path = "../ProjectChomsky/packages/chomsky-uir" }
chomsky-cost = { path = "../ProjectChomsky/packages/chomsky-cost" }
chomsky-extract = { path = "../ProjectChomsky/packages/chomsky-extract" }
chomsky-rules = { path = "../ProjectChomsky/packages/chomsky-rules" }
chomsky-rule-engine = { path = "../ProjectChomsky/packages/chomsky-rule-engine" }
oak-core = { path = "../oaks/projects/oak-core" }
oak-rust = { path = "../oaks/examples/oak-rust" }
oak-c = { path = "../oaks/examples/oak-c" }
oak-typescript = { path = "../oaks/examples/oak-typescript" }
gaia-jit = { path = "../project-gaia/projects/gaia-jit" }
gaia-types = { path = "../project-gaia/projects/gaia-types" }
gaia-assembler = { path = "../project-gaia/projects/gaia-assembler" }
pe-assembler = { path = "../project-gaia/examples/pe-assembler" }
x86_64-assembler = { path = "../project-gaia/examples/x86_64-assembler" }
nyar-vm = { path = "projects/nyar-vm" }
nyar-types = { path = "projects/nyar-types" }
nyar-aot = { path = "projects/nyar-aot" }

criterion = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
clap = { version = "4.5", features = ["derive"] }
byteorder = "1.5"
url = "2.5"
tempfile = "3.10"
