[package]
name = "nyar-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
nyar-vm = { path = "../nyar-vm" }
nyar-types = { path = "../nyar-types" }
oak-vfs = { path = "../../../oaks/projects/oak-vfs" }
serde = { workspace = true }
serde_json = { workspace = true }
