[package]
name = "rusty-r"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nyar-vm = { workspace = true }
nyar-types = { workspace = true }
oak-core = { workspace = true }
oak-r = { workspace = true }
chomsky = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-types = { workspace = true }
serde = { workspace = true }
