[package]
name = "rusty-julia"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
nyar-vm = { workspace = true }
nyar-types = { workspace = true }
oak-core = { workspace = true }
oak-vfs = { workspace = true }
oak-julia = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-types = { workspace = true }
