[package]
name = "nyar"
version = "0.1.0"
edition = "2021"

[dependencies]
nyar-vm = { workspace = true }
nyar-types = { workspace = true }
nyar-aot = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

# Frontends
rusty-c = { workspace = true }
rusty-java = { workspace = true }
rusty-python = { workspace = true }
rusty-typescript = { workspace = true }
rusty-go = { workspace = true }
rusty-csharp = { workspace = true }
rusty-tcl = { workspace = true }
rusty-swift = { workspace = true }
rusty-julia = { workspace = true }
rusty-lua = { workspace = true }
rusty-rust = { workspace = true }
rusty-zig = { workspace = true }
rusty-php = { workspace = true }
rusty-ruby = { workspace = true }
rusty-dart = { workspace = true }
rusty-nim = { workspace = true }
rusty-mojo = { workspace = true }
rusty-kotlin = { workspace = true }
