[package]
name = "nyar-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
oak-core = { workspace = true }
oak-vfs = { workspace = true }
chomsky-extract = { workspace = true }
chomsky-emit = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-types = { workspace = true }
chomsky-cost = { workspace = true }
nyar-gc = { workspace = true }

[features]
default = ["gc"]
gc = []
