[package]
name = "nyar-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
oak-core = { workspace = true }
oak-vfs = { workspace = true }
chomsky-extract = { workspace = true }
chomsky-emit = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-types = { workspace = true }
chomsky-cost = { workspace = true }
nyar-gc = { workspace = true }

[features]
default = ["gc"]
gc = []
