[package]
name = "nyar-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
thiserror = "1.0"
oak-core = { workspace = true }
chomsky-extract = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-types = { workspace = true }
chomsky-cost = { workspace = true }
nyar-gc = { path = "../nyar-gc" }

[features]
default = ["gc"]
gc = []
