[package]
name = "rusty-dart"
version = "0.1.0"
edition = "2021"

[dependencies]
nyar-vm = { path = "../../projects/nyar-vm" }
nyar-types = { path = "../../projects/nyar-types" }
oak-core = { path = "../../../oaks/projects/oak-core" }
oak-dart = { path = "../../../oaks/examples/oak-dart" }
chomsky-uir = { path = "../../../ProjectChomsky/packages/chomsky-uir" }
chomsky-source = { path = "../../../ProjectChomsky/packages/chomsky-source" }
