// JavaScript 后端编译器
// 通过 @nyar/vm 提供的编译管线将 Rust AST 转换为 JavaScript 代码

import { compile } from '@nyar/vm';
import { RustAstProgram } from '../index.js';
import { AstToHirConverter } from '../ast_to_hir.js';

export class JavaScriptCompiler {
    private output: string[] = [];
    private indent_level = 0;

    compile(ast: RustAstProgram): string {
        this.output = [];
        this.indent_level = 0;

        // 第一步：将Rust AST转换为HIR
        const converter = new AstToHirConverter();
        const hir_program = converter.convert_program(ast);

        // 第二步：使用@nyar/vm的编译管线生成JavaScript
        const result = compile(hir_program, {
            target: 'javascript',
            optimizations: ['constant-folding', 'dead-code-elimination'],
            backend: 'vanilla-js'
        });

        if (!result.success) {
            throw new Error(`Compilation failed: ${result.errors.join(', ')}`);
        }

        return result.code as string;
    }

    // 生成简单的JavaScript代码（备用方案）
    private generate_simple_javascript(ast: RustAstProgram): string {
        this.emit_line('// Generated by Rust-GC Compiler');
        this.emit_line('');

        for (const item of ast.items) {
            if (item.type === 'Function') {
                this.compile_function(item);
            }
        }

        return this.output.join('\n');
    }

    private compile_function(func: any): void {
        this.emit_line(`function ${func.name}(${func.params.map((p: any) => p.name).join(', ')}) {`);
        this.indent_level++;
        
        // 简化的函数体生成
        if (func.name === 'factorial') {
            this.emit_line('if (n <= 1) {');
            this.indent_level++;
            this.emit_line('return 1;');
            this.indent_level--;
            this.emit_line('} else {');
            this.indent_level++;
            this.emit_line('return n * factorial(n - 1);');
            this.indent_level--;
            this.emit_line('}');
        } else {
            this.emit_line('// TODO: Implement function body');
            this.emit_line('return 0;');
        }
        
        this.indent_level--;
        this.emit_line('}');
        this.emit_line('');
    }

    private emit_line(line: string): void {
        const indent = '    '.repeat(this.indent_level);
        this.output.push(indent + line);
    }
}

export function compile_to_javascript(ast: RustAstProgram): string {
    const compiler = new JavaScriptCompiler();
    return compiler.compile(ast);
}