[package]
name = "rusty-swift"
version = "0.1.0"
edition = "2021"

[dependencies]
nyar-vm = { workspace = true }
nyar-types = { workspace = true }
oak-core = { workspace = true }
oak-swift = { workspace = true }
chomsky = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-types = { workspace = true }
oak-vfs = { workspace = true }
