[package]
name = "mini-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "virtual_python"
path = "src/lib.rs"

[dependencies]
oak-python = { path = "../../../oaks/examples/oak-python" }
chomsky-full = { path = "../../../ProjectChomsky/packages/chomsky-full" }
chomsky-uast = { path = "../../../ProjectChomsky/packages/chomsky-uast" }
chomsky-source = { path = "../../../ProjectChomsky/packages/chomsky-source" }
gaia-jit = { workspace = true }
gaia-types = { workspace = true }
gaia-assembler = { workspace = true }
pe-assembler = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
rustyline = "14.0"

[[bin]]
name = "python"
path = "bin/python.rs"

[dev-dependencies]
tempfile = "3.3"
