[package]
name = "virtual-python"
version = "0.1.0"
edition = "2021"

[dependencies]
gaia-jit = { workspace = true }
gaia-types = { workspace = true }
gaia-assembler = { workspace = true }
pe-assembler = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
tempfile = "3.3"
