[package]
name = "nyar-aot"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
chomsky = { path = "../../../ProjectChomsky/packages/chomsky" }
chomsky-uir = { workspace = true }
chomsky-extract = { path = "../../../ProjectChomsky/packages/chomsky-extract" }
nyar-types = { path = "../nyar-types" }
pe-assembler = { workspace = true }
gaia-types = { workspace = true }
