[package]
name = "nyar-aot"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
chomsky = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-cost = { workspace = true }
chomsky-extract = { workspace = true }
chomsky-emit = { workspace = true }
nyar-types = { workspace = true }
oak-core = { workspace = true }
oak-vfs = { workspace = true }

[features]
default = ["native"]
native = ["chomsky/default"]
