[package]
name = "nyar-vm"
version = "0.1.0"
edition = "2021"

[lib]
name = "nyar_vm"
path = "src/lib.rs"

[dependencies]
nyar-error = { path = "../nyar-error" }
serde = { workspace = true }
toml = { workspace = true }
byteorder = { workspace = true }
zip = "0.6"

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench"
harness = false
