[package]
name = "nyar-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
nyar-gc = { path = "../nyar-gc", features = ["tokio"] }
nyar-types = { path = "../nyar-types" }
nyar-aot = { path = "../nyar-aot", default-features = false }
chomsky = { path = "../../../ProjectChomsky/packages/chomsky", default-features = false, features = ["jvm"] }
chomsky-uir = { workspace = true }
chomsky-source = { workspace = true }
chomsky-cost = { workspace = true }
chomsky-extract = { path = "../../../ProjectChomsky/packages/chomsky-extract" }
chomsky-types = { path = "../../../ProjectChomsky/packages/chomsky-types" }
byteorder = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
thiserror = "1.0"
indexmap = "2.2"
pe-assembler = { workspace = true, optional = true }
gaia-assembler = { workspace = true, optional = true }
gaia-types = { workspace = true }
x86_64-assembler = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
tokio = { version = "1.0", features = ["full"], optional = true }

[features]
default = ["native", "clap", "jvm"]
native = ["nyar-aot/native", "dep:pe-assembler", "dep:gaia-assembler", "dep:x86_64-assembler"]
jvm = ["chomsky/jvm"]
clap = ["dep:clap"]
tokio = ["dep:tokio", "nyar-gc/tokio"]
