package examples: tests;

world imports {
  import tuples;
}
// wasm-tools component embed --dummy tuples.wit -t
interface tuples {
  variant test {
    a,
    b(tuple<u8>),
    c(tuple<u8, u8, u8, u8, u8, u8, u8, u8>),
  }

  tuple0: func(x: tuple<>);
  tuple1: func(x: tuple<u8>);
  tuple2: func(x: tuple<u8, u8>);
  tuple22: func(x: tuple<tuple<u8, u8>, tuple<u8, u8>>);
  tuple4: func(x: tuple<u8, u8, u8, u8>);
  tuple16: func(x: tuple<u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8>);
  tuple17: func(x: tuple<u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8>);

  tuple-r0: func() -> tuple<>;
  tuple-r1: func() -> tuple<u8>;
  tuple-r2: func() -> tuple<u8, f32, f32>;

    test-option: func(x: option<u8>);
    test-result: func(x: result<u8, u8>);
    test-variant: func(x: test);


}

