[package]
name = "mini-lua"
version = "0.1.0"
edition = "2021"

[lib]
name = "virtual_lua"
path = "src/lib.rs"

[dependencies]
oak-lua = { path = "../../../oaks/examples/oak-lua" }
oak-core = { path = "../../../oaks/projects/oak-core" }
chomsky-full = { path = "../../../ProjectChomsky/packages/chomsky-full" }
chomsky-uir = { path = "../../../ProjectChomsky/packages/chomsky-uir" }
chomsky-source = { path = "../../../ProjectChomsky/packages/chomsky-source" }
chomsky-cost = { path = "../../../ProjectChomsky/packages/chomsky-cost" }
gaia-jit = { workspace = true }
gaia-types = { workspace = true }
gaia-assembler = { workspace = true }
pe-assembler = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
oak-repl = { path = "../../../oaks/projects/oak-repl" }
oak-highlight = { path = "../../../oaks/projects/oak-highlight" }

[[bin]]
name = "lua"
path = "bin/lua.rs"

[dev-dependencies]
tempfile = "3.3"
