[package]
name = "rusty-rust"
version = "0.1.0"
edition = "2024"
authors = ["Aster <192607617@qq.com>"]
description = "Rewrite rust in rust!"

[[bin]]
name = "rrust"
path = "src/main.rs"

[dependencies]
gaia-jit = { workspace = true }
gaia-assembler = { workspace = true, features = ["clr"] }
gaia-types = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
