[package]
name = "rusty-java"
version = "0.1.0"
edition = "2021"

[dependencies]
nyar-types = { workspace = true }
nyar-vm = { workspace = true }
oak-core = { workspace = true }
oak-vfs = { workspace = true }
oak-java = { path = "../../../oaks/examples/oak-java" }
chomsky = { path = "../../../ProjectChomsky/packages/chomsky", default-features = false, features = ["jvm"] }
chomsky-uir = { path = "../../../ProjectChomsky/packages/chomsky-uir" }
chomsky-types = { workspace = true }
chomsky-extract = { workspace = true }
chomsky-cost = { workspace = true }
tempfile = "3.3"

[[bin]]
name = "javac"
path = "bin/javac.rs"

[[bin]]
name = "java"
path = "bin/java.rs"
