[package]
name = "nyar-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nyar"
path = "src/main.rs"

[dependencies]
nyar-error = { path = "../nyar-error" }
nyar-vm = { path = "../nyar-vm" }
nyar-wasm = { path = "../nyar-wasm" }
nyar-jvm = { path = "../nyar-jvm" }
valkyrie-language = { path = "../../examples/valkyrie-language" }
clap = { workspace = true }
zip = "0.6"
