[package]
name = "rusty-csharp"
version = "0.1.0"
edition = "2021"

[lib]
name = "rusty_csharp"
path = "src/lib.rs"

[dependencies]
chomsky = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-extract = { workspace = true }
chomsky-cost = { workspace = true }
chomsky-emit = { workspace = true }
oak-core = { workspace = true }
oak-java = { workspace = true }
oak-csharp = { workspace = true }
nyar-types = { workspace = true }
nyar-vm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
tempfile = { workspace = true }
