import {DataDirectory} from "@/reader/DataDirectory";

export interface OptionalHeader {
    magic: bigint;                      // 魔数
    major_linker_version: bigint;       // 链接器主版本号
    minor_linker_version: bigint;       // 链接器次版本号
    size_of_code: bigint;               // 代码段大小
    size_of_initialized_data: bigint;   // 已初始化数据大小
    size_of_uninitialized_data: bigint; // 未初始化数据大小
    address_of_entry_point: bigint;    // 入口点地址
    base_of_code: bigint;               // 代码基址
    base_of_data: bigint;               // 数据基址（仅32位）
    image_base: bigint;                 // 镜像基址
    section_alignment: bigint;          // 段对齐
    file_alignment: bigint;             // 文件对齐
    major_operating_system_version: bigint; // 操作系统主版本号
    minor_operating_system_version: bigint; // 操作系统次版本号
    major_image_version: bigint;        // 镜像主版本号
    minor_image_version: bigint;        // 镜像次版本号
    major_subsystem_version: bigint;    // 子系统主版本号
    minor_subsystem_version: bigint;    // 子系统次版本号
    win32_version_value: bigint;        // Win32版本值
    size_of_image: bigint;              // 镜像大小
    size_of_headers: bigint;            // 头部大小
    checksum: bigint;                   // 校验和
    subsystem: bigint;                   // 子系统
    dll_characteristics: bigint;        // DLL特征
    size_of_stack_reserve: bigint;       // 栈保留大小
    size_of_stack_commit: bigint;        // 栈提交大小
    size_of_heap_reserve: bigint;       // 堆保留大小
    size_of_heap_commit: bigint;        // 堆提交大小
    loader_flags: bigint;               // 加载器标志
    number_of_rva_and_sizes: bigint;    // RVA和数量
    data_directories: DataDirectory[];  // 数据目录
}