[package]
name = "mini-typescript"
version = "0.1.0"
edition = "2021"

[dependencies]
oak-typescript = { path = "../../../oaks/examples/oak-typescript" }
chomsky-full = { path = "../../../ProjectChomsky/packages/chomsky-full" }
chomsky-uast = { path = "../../../ProjectChomsky/packages/chomsky-uast" }
chomsky-types = { path = "../../../ProjectChomsky/packages/chomsky-types" }
chomsky-source = { path = "../../../ProjectChomsky/packages/chomsky-source" }
gaia-jit = { workspace = true }
gaia-types = { workspace = true }
gaia-assembler = { workspace = true }
pe-assembler = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
rustyline = "14.0"

[[bin]]
name = "tsc"
path = "bin/tsc.rs"

[[bin]]
name = "tsx"
path = "bin/tsx.rs"

[dev-dependencies]
tempfile = "3.3"
