[package]
name = "nyar-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
chomsky = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-rules = { workspace = true }
chomsky-rule-engine = { workspace = true }
gaia-jit = { workspace = true }
nyar-types = { workspace = true }
nyar-vm = { workspace = true }
hashbrown = { workspace = true }
dashmap = { workspace = true }
