[package]
name = "nyar-jit"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chomsky = { workspace = true }
chomsky-uir = { workspace = true }
chomsky-rules = { workspace = true }
chomsky-rule-engine = { workspace = true }
gaia-jit = { workspace = true }
nyar-types = { workspace = true }
nyar-vm = { workspace = true }
hashbrown = { workspace = true }
dashmap = { workspace = true }
