[package]
name = "nyar-gc"
version = "0.1.0"
edition = "2021"

[dependencies]
nyar-macros = { workspace = true }
tokio = { workspace = true, optional = true }
once_cell = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }

[features]
default = []
tokio = ["dep:tokio"]
