[package]
name = "mini-nim"
version = "0.1.0"
edition = "2021"

[dependencies]
nyar-vm = { path = "../../projects/nyar-vm" }
nyar-types = { path = "../../projects/nyar-types" }
oak-core = { path = "../../../oaks/projects/oak-core" }
oak-nim = { path = "../../../oaks/examples/oak-nim" }
chomsky-uir = { path = "../../../ProjectChomsky/packages/chomsky-uir" }
chomsky-source = { path = "../../../ProjectChomsky/packages/chomsky-source" }
serde = { version = "1.0", features = ["derive"] }
